Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "../shared", "/shared/global", owner: "vagrant"
  config.vm.synced_folder "./shared", "/shared/ubuntu", owner: "vagrant"
  config.vm.synced_folder "." "/vagrant", disabled: true  # doesn't work for some fucking reason
  
  config.vm.provision "shell", path: "./shared/global.sh"
  
  config.vm.define "dev-linux" do |dvm|
    dvm.vm.box = "chenhan/ubuntu-desktop-20.04"
    dvm.vm.box_version = "20200424"

    dvm.vm.network "private_network", ip: "172.16.0.101"
    dvm.vm.network "public_network", ip: "192.168.0.78"  # this one's up to you, could use dhcp if unsure about a static IP

    # main development machine, should have access to all others for the sake of git if nothing else
    dvm.vm.synced_folder "../", "/shared/VMs", owner: "vagrant"
    dvm.vm.provision "shell", path: "../shared/self-ansible_linux.sh"

    dvm.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 4
      vb.name = "Dev-Linux"
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected3", "on"]
      vb.customize ["storageattach", :id, "--storagectl", "IDE Controller",
                    "--port", "0", "--device", "1",
                    "--type", "dvddrive",
                    "--medium", "emptydrive"]
    end
  end
  
  config.vm.define "ansible" do |ans|
    ans.vm.network "private_network", ip: "172.16.0.100"
    ans.vm.provision "shell", path: "./shared/ansible.sh"

    ans.vm.provider "virtualbox" do |vb|
      vb.memory = 768
      vb.cpus = 2
      vb.name = "Ansible"
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
    end
  end
end