---
- name: Global VM provisioning play
  hosts: all
  roles:
    - role: global
      tags:
        - general
        - game-server
    
    - role: dev_master
      tags: dev-master
    
    - role: mysql_install
      tags: db-mysql
    
    # gaming
    - role: game_server
      tags: game-server
  