---
- hosts: terraria
  vars:
    gs_overwrite: yes
    gs_type: terraria
    gs_install_zerotier: false
    gs_server_ip: update
    gs_terraria_link: "https://terraria.org/system/dedicated_servers/archives/000/000/043/original/terraria-server-142.zip?1617024229"
  
  pre_tasks:
    - name: Load variables
      ignore_errors: yes
      include_vars:
        file: "../private/{{ ansible_host }}_terraria-variables.yml"

  roles:
    - role: game_server
      become: yes