---
# - name: Install software properties common
#   apt:
#     name: software-properties-common
#     state: latest
#     update_cache: yes

# - name: Add deadsnakes repo
#   apt_repository:
#     repo: 'ppa:deadsnakes/ppa'
#     state: present
#     update_cache: yes
#     validate_certs: false

# - name: Update Python
#   apt:
#     name: 'python3.9'
#     state: latest

- name: Install Python 3 dependencies
  apt:
    name: "{{ devinstall_python['dependencies'] }}"
    state: latest
    update_cache: yes

- name: Destroy previous temporary folder, if existing
  file:
    path: '/devinstall_tmp'
    state: absent

- name: Create temporary folder
  file:
    path: '/devinstall_tmp'
    state: directory

# - name: Download Python release
#   get_url:
#     dest: /devinstall_tmp
#     url: "{{ devinstall_latest_python3 }}"

- name: Extract Python release
  unarchive:
    remote_src: yes
    src: "{{ devinstall_python['url'] }}"
    dest: '/devinstall_tmp'

- name: Run Python configure
  shell:
    chdir: "/devinstall_tmp/{{ devinstall_python_dir }}"
    cmd: "./configure --enable-optimizations"

- name: Install Python from source
  make:
    chdir: "/devinstall_tmp/{{ devinstall_python_dir }}"
    target: install

- name: Recursively delete temporary folder
  file:
    path: '/devinstall_tmp'
    state: absent
