---
- name: Install software properties common
  apt:
    name: software-properties-common
    state: latest
    update_cache: yes

- name: Add deadsnakes repo
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    state: present
    update_cache: yes
    validate_certs: false

- name: Update Python
  apt:
    name: 'python3.9'
    state: latest
