---
- name: Probe current Python install
  shell: python3 --version
  register: global_pyver

- name: Update Python
  vars:
    global_python_version: "{{ global_pyver['stdout'].split()[-1] | regex_replace('\\.', '') | int }}"
  when: global_python_version < global_python_latest
  block:
    - name: Install Python 3 dependencies
      package:
        name: "{{ global_pydependency }}"
        state: present
      loop: "{{ global_python['dependencies'] }}"
      loop_control:
        loop_var: global_pydependency

    - name: Extract Python release
      unarchive:
        remote_src: yes
        src: "{{ global_python['url'] }}"
        dest: '/tmp'

    - name: Run Python configure
      shell:
        chdir: "/tmp/{{ global_python_dir }}"
        cmd: "./configure --enable-optimizations"

    - name: Install Python from source
      make:
        chdir: "/tmp/{{ global_python_dir }}"
        target: install
      become: yes
