---
- name: Check for ZeroTier install
  stat:
    path: /usr/local/bin/zerotier-one
  register: gs_ztinstall

- name: Install ZeroTier One
  when: not gs_ztinstall.stat.exists
  block:
    # environment variables are a pain on linux for now, i'll stick to files
    - name: Look up variables from secrets
      include_vars:
        file: '../../../../private/secrets.yml'

    - git:
        accept_hostkey: yes
        repo: 'https://github.com/zerotier/ZeroTierOne.git'
        dest: '/tmp/ZeroTierOne'

    - make:
        chdir: '/tmp/ZeroTierOne'

    - make:
        chdir: '/tmp/ZeroTierOne'
        target: install
      become: yes
    
    - shell: "zerotier-one -d && zerotier-one -i generate"
      changed_when: no
      
    - shell: "zerotier-one -q -j join {{ game_server['zt_network'] }}"
      when: game_server['zt_network'] is defined
      become: yes
      changed_when: no

- name: Fetch ZeroTier IP when available
  block:
    - copy:
        src: fetch-ip.sh
        dest: /tmp/fetch-ip.sh
        mode: '0777'
    
    - shell:
        cmd: nohup /tmp/fetch-ip.sh &
      become: yes
