---
- name: Fail on non-Ubuntu host
  fail:
    msg: This role only supports Ubuntu hosts
  when: ansible_lsb['id'] | lower != "ubuntu"

- block:
    - name: Import add keys task
      import_tasks: 'add_keys.yml'

    - name: Import install task
      import_tasks: 'install.yml'
  become: yes
...
